allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - lightningcss
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - better-auth-bili-basic
  - '@better-auth/core@1.7.1'
  - '@better-auth/drizzle-adapter@1.7.1'
  - '@better-auth/kysely-adapter@1.7.1'
  - '@better-auth/memory-adapter@1.7.1'
  - '@better-auth/mongo-adapter@1.7.1'
  - '@better-auth/oauth-provider@1.7.1'
  - '@better-auth/passkey@1.7.1'
  - '@better-auth/prisma-adapter@1.7.1'
  - '@better-auth/telemetry@1.7.1'
  - better-auth@1.7.1
