/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AbuseRouteImport } from './routes/abuse'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as InitRouteImport } from './routes/init'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiBiliInfoRouteImport } from './routes/api/bili-info'
import { Route as ApiResolveB23RouteImport } from './routes/api/resolve-b23'
import { Route as ApiTurnstileRouteImport } from './routes/api/turnstile'
import { Route as DeviceConfirmRouteImport } from './routes/device/confirm'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as Oauth2SplatRouteImport } from './routes/oauth2/$'
import { Route as ApiAdminClientsRouteImport } from './routes/api/admin/clients'
import { Route as ApiAdminInitRouteImport } from './routes/api/admin/init'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AbuseRoute = AbuseRouteImport.update({
  id: '/abuse',
  path: '/abuse',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBiliInfoRoute = ApiBiliInfoRouteImport.update({
  id: '/api/bili-info',
  path: '/api/bili-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveB23Route = ApiResolveB23RouteImport.update({
  id: '/api/resolve-b23',
  path: '/api/resolve-b23',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTurnstileRoute = ApiTurnstileRouteImport.update({
  id: '/api/turnstile',
  path: '/api/turnstile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceConfirmRoute = DeviceConfirmRouteImport.update({
  id: '/device/confirm',
  path: '/device/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2SplatRoute = Oauth2SplatRouteImport.update({
  id: '/oauth2/$',
  path: '/oauth2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClientsRoute = ApiAdminClientsRouteImport.update({
  id: '/api/admin/clients',
  path: '/api/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInitRoute = ApiAdminInitRouteImport.update({
  id: '/api/admin/init',
  path: '/api/admin/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/abuse': typeof AbuseRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/docs': typeof DocsRoute
  '/error': typeof ErrorRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/verify': typeof VerifyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bili-info': typeof ApiBiliInfoRoute
  '/api/resolve-b23': typeof ApiResolveB23Route
  '/api/turnstile': typeof ApiTurnstileRoute
  '/device/confirm': typeof DeviceConfirmRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/init': typeof ApiAdminInitRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/abuse': typeof AbuseRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/docs': typeof DocsRoute
  '/error': typeof ErrorRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/verify': typeof VerifyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bili-info': typeof ApiBiliInfoRoute
  '/api/resolve-b23': typeof ApiResolveB23Route
  '/api/turnstile': typeof ApiTurnstileRoute
  '/device/confirm': typeof DeviceConfirmRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/init': typeof ApiAdminInitRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/abuse': typeof AbuseRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/docs': typeof DocsRoute
  '/error': typeof ErrorRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/verify': typeof VerifyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/bili-info': typeof ApiBiliInfoRoute
  '/api/resolve-b23': typeof ApiResolveB23Route
  '/api/turnstile': typeof ApiTurnstileRoute
  '/device/confirm': typeof DeviceConfirmRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/api/admin/clients': typeof ApiAdminClientsRoute
  '/api/admin/init': typeof ApiAdminInitRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/abuse'
    | '/dashboard'
    | '/developer'
    | '/docs'
    | '/error'
    | '/init'
    | '/login'
    | '/mcp'
    | '/verify'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/bili-info'
    | '/api/resolve-b23'
    | '/api/turnstile'
    | '/device/confirm'
    | '/oauth/consent'
    | '/oauth2/$'
    | '/api/admin/clients'
    | '/api/admin/init'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/abuse'
    | '/dashboard'
    | '/developer'
    | '/docs'
    | '/error'
    | '/init'
    | '/login'
    | '/mcp'
    | '/verify'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/bili-info'
    | '/api/resolve-b23'
    | '/api/turnstile'
    | '/device/confirm'
    | '/oauth/consent'
    | '/oauth2/$'
    | '/api/admin/clients'
    | '/api/admin/init'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/abuse'
    | '/dashboard'
    | '/developer'
    | '/docs'
    | '/error'
    | '/init'
    | '/login'
    | '/mcp'
    | '/verify'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/bili-info'
    | '/api/resolve-b23'
    | '/api/turnstile'
    | '/device/confirm'
    | '/oauth/consent'
    | '/oauth2/$'
    | '/api/admin/clients'
    | '/api/admin/init'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AbuseRoute: typeof AbuseRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  DocsRoute: typeof DocsRoute
  ErrorRoute: typeof ErrorRoute
  InitRoute: typeof InitRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  VerifyRoute: typeof VerifyRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiBiliInfoRoute: typeof ApiBiliInfoRoute
  ApiResolveB23Route: typeof ApiResolveB23Route
  ApiTurnstileRoute: typeof ApiTurnstileRoute
  DeviceConfirmRoute: typeof DeviceConfirmRoute
  OauthConsentRoute: typeof OauthConsentRoute
  Oauth2SplatRoute: typeof Oauth2SplatRoute
  ApiAdminClientsRoute: typeof ApiAdminClientsRoute
  ApiAdminInitRoute: typeof ApiAdminInitRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abuse': {
      id: '/abuse'
      path: '/abuse'
      fullPath: '/abuse'
      preLoaderRoute: typeof AbuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bili-info': {
      id: '/api/bili-info'
      path: '/api/bili-info'
      fullPath: '/api/bili-info'
      preLoaderRoute: typeof ApiBiliInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve-b23': {
      id: '/api/resolve-b23'
      path: '/api/resolve-b23'
      fullPath: '/api/resolve-b23'
      preLoaderRoute: typeof ApiResolveB23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/turnstile': {
      id: '/api/turnstile'
      path: '/api/turnstile'
      fullPath: '/api/turnstile'
      preLoaderRoute: typeof ApiTurnstileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/confirm': {
      id: '/device/confirm'
      path: '/device/confirm'
      fullPath: '/device/confirm'
      preLoaderRoute: typeof DeviceConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/$': {
      id: '/oauth2/$'
      path: '/oauth2/$'
      fullPath: '/oauth2/$'
      preLoaderRoute: typeof Oauth2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/clients': {
      id: '/api/admin/clients'
      path: '/api/admin/clients'
      fullPath: '/api/admin/clients'
      preLoaderRoute: typeof ApiAdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/init': {
      id: '/api/admin/init'
      path: '/api/admin/init'
      fullPath: '/api/admin/init'
      preLoaderRoute: typeof ApiAdminInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AbuseRoute: AbuseRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  DocsRoute: DocsRoute,
  ErrorRoute: ErrorRoute,
  InitRoute: InitRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  VerifyRoute: VerifyRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiBiliInfoRoute: ApiBiliInfoRoute,
  ApiResolveB23Route: ApiResolveB23Route,
  ApiTurnstileRoute: ApiTurnstileRoute,
  DeviceConfirmRoute: DeviceConfirmRoute,
  OauthConsentRoute: OauthConsentRoute,
  Oauth2SplatRoute: Oauth2SplatRoute,
  ApiAdminClientsRoute: ApiAdminClientsRoute,
  ApiAdminInitRoute: ApiAdminInitRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
